# Generated by Django 3.0.8 on 2021-04-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textPost', models.TextField()),
                ('like', models.IntegerField()),
                ('unlike', models.IntegerField()),
            ],
        ),
    ]
