# Generated by Django 3.0.8 on 2021-04-30 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postData', '0002_post_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='unlike',
            new_name='dislike',
        ),
    ]
