# Generated by Django 3.0.8 on 2021-04-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postData', '0003_auto_20210430_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dislike',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
